version: '3.7'

services:
  jetset-fe:
    ports:
      - 80:80
      - 443:443
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./nginx.conf:/etc/nginx/user.conf.d/nginx_template.conf
      - ./letsencrypt:/etc/letsencrypt
