import { IValues } from './types'

export const values: IValues = {
  // Aircraft Summary

  serialNumber: '',
  registrationNumber: '',
  flightRules: '',
  flightDeck: '',
  airframeTtsn: null,
  landings: '',
  configuration: '',
  landingGear: '',
  totalSeats: '',
  crewSeats: '',
  passengerSeats: '',
  totalTime: '',

  // Engine

  engineMake: '',
  engineModel: '',
  engineTbo: '',
  engineN1Ttsn: '',
  engineN1Tsox: '',
  engineN1ShsiTop: '',
  engineN1Ttox: '',
  engineN1Csn: '',
  engineN1Csoh: '',
  engineN2Ttsn: '',
  engineN2Tsox: '',
  engineN2ShsiTop: '',
  engineN2Ttox: '',
  engineN2Csn: '',
  engineN2Csoh: '',
  engineN3Ttsn: '',
  engineN3Tsox: '',
  engineN3ShsiTop: '',
  engineN3Ttox: '',
  engineN3Csn: '',
  engineN3Csoh: '',
  engineN4Ttsn: '',
  engineN4Tsox: '',
  engineN4ShsiTop: '',
  engineN4Ttox: '',
  engineN4Csn: '',
  engineN4Csoh: '',
  engineN1Sn: '',
  engineN2Sn: '',
  engineN3Sn: '',
  engineN4Sn: '',
  engineHpThrust: '',

  // APU

  apuMake: '',
  apuModel: '',
  apuTbo: '',
  apuTtsn: '',
  apuTsoh: '',
  apuCsn: '',
  apuCsoh: '',
  apuSn: '',

  // Propeller

  propMake: '',
  propType: '',
  propModel: '',
  propSize: '',
  propTboHrs: '',
  propTboYrs: '',
  prop1Sn: '',
  prop1Ttsn: '',
  prop1Tsoh: '',
  prop1Ttoh: '',
  prop1OhYr: '',
  prop1OhDue: '',
  prop2Sn: '',
  prop2Ttsn: '',
  prop2Tsoh: '',
  prop2Ttoh: '',
  prop2OhYr: '',
  prop2OhDue: '',

  // Avionics

  fmsN: '',
  fms: '',
  engMonitor: '',
  gpsN: '',
  gpsModel1: '',
  gpsModel2: '',
  autopilot: '',
  autopilotN: '',
  wxRadar: '',
  transponderN: '',
  transponder1: '',
  transponder2: '',
  vhfComN: '',
  vhfComModel1: '',
  vhfComModel2: '',
  vhfNavN: '',
  vhfNavModel1: '',
  vhfNavModel2: '',

  // Maintenance

  mtxTracking: '',
  airframeProgram: '',
  engineProgram: '',
  apuProgram: '',
  avionicsProgram: '',
  mtxCondition: '',
  annualDue: '',
  cCheckDue: '',
  lGearOhDue: '',
  inspectionStatus: '',
  lastPerformed: '',
  nextDue: '',
  warrantyAfYr: '',
  warrantyEngYr: '',
  warrantyAfHrs: '',
  warrantyEngHrs: '',
  warrantyAviYr: '',
  warrantyApuYr: '',
  warrantyPropYr: '',
  warrantyPropHrs: '',

  // Exterior/Cabin

  exteriorColor: '',
  exteriorDetail: '',
  exteriorYear: '',
  interiorColor: '',
  interiorFinish: '',
  interiorYear: '',
  galleyLocation: '',
  lavLocation: '',
  lavDescription: '',
  crewRest: null,
  jumpSeat: null,
  wifiConnectivity: '',

  // Weights/other

  maxRamp: '',
  mtow: '',
  mlv: '',
  mzvf: '',
  bew: '',
  bow: '',
  fuelCapacity: '',
  payload: '',
  usefulLoad: '',
  floatModel: '',
  bewFloats: '',
  usefulLoadFloats: '',
  oxygenTank: '',
  fuelCapacityGal: '',
}
